# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/krzysiek/Desktop/MyApp/EscapeLinez

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/krzysiek/Desktop/MyApp/EscapeLinez

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/krzysiek/Desktop/MyApp/EscapeLinez/CMakeFiles /home/krzysiek/Desktop/MyApp/EscapeLinez/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/krzysiek/Desktop/MyApp/EscapeLinez/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named EscapeLinez

# Build rule for target.
EscapeLinez: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 EscapeLinez
.PHONY : EscapeLinez

# fast build rule for target.
EscapeLinez/fast:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/build
.PHONY : EscapeLinez/fast

src/Button.o: src/Button.cpp.o

.PHONY : src/Button.o

# target to build an object file
src/Button.cpp.o:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Button.cpp.o
.PHONY : src/Button.cpp.o

src/Button.i: src/Button.cpp.i

.PHONY : src/Button.i

# target to preprocess a source file
src/Button.cpp.i:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Button.cpp.i
.PHONY : src/Button.cpp.i

src/Button.s: src/Button.cpp.s

.PHONY : src/Button.s

# target to generate assembly for a file
src/Button.cpp.s:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Button.cpp.s
.PHONY : src/Button.cpp.s

src/CatchMe.o: src/CatchMe.cpp.o

.PHONY : src/CatchMe.o

# target to build an object file
src/CatchMe.cpp.o:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/CatchMe.cpp.o
.PHONY : src/CatchMe.cpp.o

src/CatchMe.i: src/CatchMe.cpp.i

.PHONY : src/CatchMe.i

# target to preprocess a source file
src/CatchMe.cpp.i:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/CatchMe.cpp.i
.PHONY : src/CatchMe.cpp.i

src/CatchMe.s: src/CatchMe.cpp.s

.PHONY : src/CatchMe.s

# target to generate assembly for a file
src/CatchMe.cpp.s:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/CatchMe.cpp.s
.PHONY : src/CatchMe.cpp.s

src/ConfigFile.o: src/ConfigFile.cpp.o

.PHONY : src/ConfigFile.o

# target to build an object file
src/ConfigFile.cpp.o:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/ConfigFile.cpp.o
.PHONY : src/ConfigFile.cpp.o

src/ConfigFile.i: src/ConfigFile.cpp.i

.PHONY : src/ConfigFile.i

# target to preprocess a source file
src/ConfigFile.cpp.i:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/ConfigFile.cpp.i
.PHONY : src/ConfigFile.cpp.i

src/ConfigFile.s: src/ConfigFile.cpp.s

.PHONY : src/ConfigFile.s

# target to generate assembly for a file
src/ConfigFile.cpp.s:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/ConfigFile.cpp.s
.PHONY : src/ConfigFile.cpp.s

src/FindThe.o: src/FindThe.cpp.o

.PHONY : src/FindThe.o

# target to build an object file
src/FindThe.cpp.o:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/FindThe.cpp.o
.PHONY : src/FindThe.cpp.o

src/FindThe.i: src/FindThe.cpp.i

.PHONY : src/FindThe.i

# target to preprocess a source file
src/FindThe.cpp.i:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/FindThe.cpp.i
.PHONY : src/FindThe.cpp.i

src/FindThe.s: src/FindThe.cpp.s

.PHONY : src/FindThe.s

# target to generate assembly for a file
src/FindThe.cpp.s:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/FindThe.cpp.s
.PHONY : src/FindThe.cpp.s

src/Font.o: src/Font.cpp.o

.PHONY : src/Font.o

# target to build an object file
src/Font.cpp.o:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Font.cpp.o
.PHONY : src/Font.cpp.o

src/Font.i: src/Font.cpp.i

.PHONY : src/Font.i

# target to preprocess a source file
src/Font.cpp.i:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Font.cpp.i
.PHONY : src/Font.cpp.i

src/Font.s: src/Font.cpp.s

.PHONY : src/Font.s

# target to generate assembly for a file
src/Font.cpp.s:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Font.cpp.s
.PHONY : src/Font.cpp.s

src/Game.o: src/Game.cpp.o

.PHONY : src/Game.o

# target to build an object file
src/Game.cpp.o:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Game.cpp.o
.PHONY : src/Game.cpp.o

src/Game.i: src/Game.cpp.i

.PHONY : src/Game.i

# target to preprocess a source file
src/Game.cpp.i:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Game.cpp.i
.PHONY : src/Game.cpp.i

src/Game.s: src/Game.cpp.s

.PHONY : src/Game.s

# target to generate assembly for a file
src/Game.cpp.s:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Game.cpp.s
.PHONY : src/Game.cpp.s

src/Line.o: src/Line.cpp.o

.PHONY : src/Line.o

# target to build an object file
src/Line.cpp.o:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Line.cpp.o
.PHONY : src/Line.cpp.o

src/Line.i: src/Line.cpp.i

.PHONY : src/Line.i

# target to preprocess a source file
src/Line.cpp.i:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Line.cpp.i
.PHONY : src/Line.cpp.i

src/Line.s: src/Line.cpp.s

.PHONY : src/Line.s

# target to generate assembly for a file
src/Line.cpp.s:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Line.cpp.s
.PHONY : src/Line.cpp.s

src/Login.o: src/Login.cpp.o

.PHONY : src/Login.o

# target to build an object file
src/Login.cpp.o:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Login.cpp.o
.PHONY : src/Login.cpp.o

src/Login.i: src/Login.cpp.i

.PHONY : src/Login.i

# target to preprocess a source file
src/Login.cpp.i:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Login.cpp.i
.PHONY : src/Login.cpp.i

src/Login.s: src/Login.cpp.s

.PHONY : src/Login.s

# target to generate assembly for a file
src/Login.cpp.s:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Login.cpp.s
.PHONY : src/Login.cpp.s

src/Menu.o: src/Menu.cpp.o

.PHONY : src/Menu.o

# target to build an object file
src/Menu.cpp.o:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Menu.cpp.o
.PHONY : src/Menu.cpp.o

src/Menu.i: src/Menu.cpp.i

.PHONY : src/Menu.i

# target to preprocess a source file
src/Menu.cpp.i:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Menu.cpp.i
.PHONY : src/Menu.cpp.i

src/Menu.s: src/Menu.cpp.s

.PHONY : src/Menu.s

# target to generate assembly for a file
src/Menu.cpp.s:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Menu.cpp.s
.PHONY : src/Menu.cpp.s

src/Mouse.o: src/Mouse.cpp.o

.PHONY : src/Mouse.o

# target to build an object file
src/Mouse.cpp.o:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Mouse.cpp.o
.PHONY : src/Mouse.cpp.o

src/Mouse.i: src/Mouse.cpp.i

.PHONY : src/Mouse.i

# target to preprocess a source file
src/Mouse.cpp.i:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Mouse.cpp.i
.PHONY : src/Mouse.cpp.i

src/Mouse.s: src/Mouse.cpp.s

.PHONY : src/Mouse.s

# target to generate assembly for a file
src/Mouse.cpp.s:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Mouse.cpp.s
.PHONY : src/Mouse.cpp.s

src/Multiplayer.o: src/Multiplayer.cpp.o

.PHONY : src/Multiplayer.o

# target to build an object file
src/Multiplayer.cpp.o:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Multiplayer.cpp.o
.PHONY : src/Multiplayer.cpp.o

src/Multiplayer.i: src/Multiplayer.cpp.i

.PHONY : src/Multiplayer.i

# target to preprocess a source file
src/Multiplayer.cpp.i:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Multiplayer.cpp.i
.PHONY : src/Multiplayer.cpp.i

src/Multiplayer.s: src/Multiplayer.cpp.s

.PHONY : src/Multiplayer.s

# target to generate assembly for a file
src/Multiplayer.cpp.s:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Multiplayer.cpp.s
.PHONY : src/Multiplayer.cpp.s

src/Network.o: src/Network.cpp.o

.PHONY : src/Network.o

# target to build an object file
src/Network.cpp.o:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Network.cpp.o
.PHONY : src/Network.cpp.o

src/Network.i: src/Network.cpp.i

.PHONY : src/Network.i

# target to preprocess a source file
src/Network.cpp.i:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Network.cpp.i
.PHONY : src/Network.cpp.i

src/Network.s: src/Network.cpp.s

.PHONY : src/Network.s

# target to generate assembly for a file
src/Network.cpp.s:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Network.cpp.s
.PHONY : src/Network.cpp.s

src/OfflineMod.o: src/OfflineMod.cpp.o

.PHONY : src/OfflineMod.o

# target to build an object file
src/OfflineMod.cpp.o:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/OfflineMod.cpp.o
.PHONY : src/OfflineMod.cpp.o

src/OfflineMod.i: src/OfflineMod.cpp.i

.PHONY : src/OfflineMod.i

# target to preprocess a source file
src/OfflineMod.cpp.i:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/OfflineMod.cpp.i
.PHONY : src/OfflineMod.cpp.i

src/OfflineMod.s: src/OfflineMod.cpp.s

.PHONY : src/OfflineMod.s

# target to generate assembly for a file
src/OfflineMod.cpp.s:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/OfflineMod.cpp.s
.PHONY : src/OfflineMod.cpp.s

src/Renderer.o: src/Renderer.cpp.o

.PHONY : src/Renderer.o

# target to build an object file
src/Renderer.cpp.o:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Renderer.cpp.o
.PHONY : src/Renderer.cpp.o

src/Renderer.i: src/Renderer.cpp.i

.PHONY : src/Renderer.i

# target to preprocess a source file
src/Renderer.cpp.i:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Renderer.cpp.i
.PHONY : src/Renderer.cpp.i

src/Renderer.s: src/Renderer.cpp.s

.PHONY : src/Renderer.s

# target to generate assembly for a file
src/Renderer.cpp.s:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Renderer.cpp.s
.PHONY : src/Renderer.cpp.s

src/Settings.o: src/Settings.cpp.o

.PHONY : src/Settings.o

# target to build an object file
src/Settings.cpp.o:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Settings.cpp.o
.PHONY : src/Settings.cpp.o

src/Settings.i: src/Settings.cpp.i

.PHONY : src/Settings.i

# target to preprocess a source file
src/Settings.cpp.i:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Settings.cpp.i
.PHONY : src/Settings.cpp.i

src/Settings.s: src/Settings.cpp.s

.PHONY : src/Settings.s

# target to generate assembly for a file
src/Settings.cpp.s:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Settings.cpp.s
.PHONY : src/Settings.cpp.s

src/Text.o: src/Text.cpp.o

.PHONY : src/Text.o

# target to build an object file
src/Text.cpp.o:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Text.cpp.o
.PHONY : src/Text.cpp.o

src/Text.i: src/Text.cpp.i

.PHONY : src/Text.i

# target to preprocess a source file
src/Text.cpp.i:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Text.cpp.i
.PHONY : src/Text.cpp.i

src/Text.s: src/Text.cpp.s

.PHONY : src/Text.s

# target to generate assembly for a file
src/Text.cpp.s:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/Text.cpp.s
.PHONY : src/Text.cpp.s

src/TextureLoader.o: src/TextureLoader.cpp.o

.PHONY : src/TextureLoader.o

# target to build an object file
src/TextureLoader.cpp.o:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/TextureLoader.cpp.o
.PHONY : src/TextureLoader.cpp.o

src/TextureLoader.i: src/TextureLoader.cpp.i

.PHONY : src/TextureLoader.i

# target to preprocess a source file
src/TextureLoader.cpp.i:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/TextureLoader.cpp.i
.PHONY : src/TextureLoader.cpp.i

src/TextureLoader.s: src/TextureLoader.cpp.s

.PHONY : src/TextureLoader.s

# target to generate assembly for a file
src/TextureLoader.cpp.s:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/TextureLoader.cpp.s
.PHONY : src/TextureLoader.cpp.s

src/WaitingRoom.o: src/WaitingRoom.cpp.o

.PHONY : src/WaitingRoom.o

# target to build an object file
src/WaitingRoom.cpp.o:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/WaitingRoom.cpp.o
.PHONY : src/WaitingRoom.cpp.o

src/WaitingRoom.i: src/WaitingRoom.cpp.i

.PHONY : src/WaitingRoom.i

# target to preprocess a source file
src/WaitingRoom.cpp.i:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/WaitingRoom.cpp.i
.PHONY : src/WaitingRoom.cpp.i

src/WaitingRoom.s: src/WaitingRoom.cpp.s

.PHONY : src/WaitingRoom.s

# target to generate assembly for a file
src/WaitingRoom.cpp.s:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/WaitingRoom.cpp.s
.PHONY : src/WaitingRoom.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/EscapeLinez.dir/build.make CMakeFiles/EscapeLinez.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... EscapeLinez"
	@echo "... edit_cache"
	@echo "... src/Button.o"
	@echo "... src/Button.i"
	@echo "... src/Button.s"
	@echo "... src/CatchMe.o"
	@echo "... src/CatchMe.i"
	@echo "... src/CatchMe.s"
	@echo "... src/ConfigFile.o"
	@echo "... src/ConfigFile.i"
	@echo "... src/ConfigFile.s"
	@echo "... src/FindThe.o"
	@echo "... src/FindThe.i"
	@echo "... src/FindThe.s"
	@echo "... src/Font.o"
	@echo "... src/Font.i"
	@echo "... src/Font.s"
	@echo "... src/Game.o"
	@echo "... src/Game.i"
	@echo "... src/Game.s"
	@echo "... src/Line.o"
	@echo "... src/Line.i"
	@echo "... src/Line.s"
	@echo "... src/Login.o"
	@echo "... src/Login.i"
	@echo "... src/Login.s"
	@echo "... src/Menu.o"
	@echo "... src/Menu.i"
	@echo "... src/Menu.s"
	@echo "... src/Mouse.o"
	@echo "... src/Mouse.i"
	@echo "... src/Mouse.s"
	@echo "... src/Multiplayer.o"
	@echo "... src/Multiplayer.i"
	@echo "... src/Multiplayer.s"
	@echo "... src/Network.o"
	@echo "... src/Network.i"
	@echo "... src/Network.s"
	@echo "... src/OfflineMod.o"
	@echo "... src/OfflineMod.i"
	@echo "... src/OfflineMod.s"
	@echo "... src/Renderer.o"
	@echo "... src/Renderer.i"
	@echo "... src/Renderer.s"
	@echo "... src/Settings.o"
	@echo "... src/Settings.i"
	@echo "... src/Settings.s"
	@echo "... src/Text.o"
	@echo "... src/Text.i"
	@echo "... src/Text.s"
	@echo "... src/TextureLoader.o"
	@echo "... src/TextureLoader.i"
	@echo "... src/TextureLoader.s"
	@echo "... src/WaitingRoom.o"
	@echo "... src/WaitingRoom.i"
	@echo "... src/WaitingRoom.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

